export const RootLayoutMetadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // metadataBase, applicationName, authors, generator, keywords, referrer, themeColor, colorScheme, viewport, creator, publisher, robots, alternates, appleWebApp, icons, manifest, twitter, verification, formatDetection, itunes, abstract, appLinks, archives, assets, bookmarks, category, classification, other
};
