[build]
  command = "npm run build"
  publish = "output/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/v1/*"
  to = "https://jsugauta1.pythonanywhere.com/:splat"
  status = 200
  force = true